name: Run Inactivity Bot

on:
  push:
    branches:
      - main

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the bot script
      - name: Run InactivityBot
        run: |
          python InactivityBot.py

      # Commit and push changes, including .log files
      - name: Commit and push changes
        run: |
          git add .  # This includes all files, including .log files
          git commit -m "Automatic update: Warned users list and logs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
