name: Run Inactivity Bot

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI
jobs:
  run_bot:
    environment: Run the bot
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the bot script
      - name: Run InactivityBot
        env:
            BOT_USERNAME: ${{ vars.BOT_USERNAME }}
            BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          python InactivityBot.py

      # Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Commit and push changes, including .log files
      - name: Commit and push changes
        run: |
          git add .  # This includes all files, including .log files
          git commit -m "Automatic update: Warned users list and logs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
