name: Run Inactivity Bot

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  run:
    environment: Run the bot
    runs-on: ubuntu-latest
    
    steps:
      # Check out your repo
      - uses: actions/checkout@v3

      # Set up Python 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "no requirements.txt"

      # Run the script
      - name: Run the bot
        env:
            BOT_USERNAME: ${{ env.BOT_USERNAME }}
            BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          python InactivityBot.py  

      # Commit and push updated JSON files
      - name: Commit and push JSON files
        run: |
          git config --global user.name "younginspiration"
          git config --global user.email "theastorpastor@gmail.com"
          git add data/*.json   
          git commit -m "Update JSON files after bot run"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

